routes/web.php
<?php

use App\Page;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
Route::get('route', function () {
	$getRouteList = array();
	$routes = Route::getRoutes();
	foreach ($routes as $route) {
		if ($route->methods()[0] == "GET" && (strpos($route->uri, 'admin') === false)) {

			$getRouteList[]['title'] = explode('/', $route->uri)[0];
		}
		/** @var \Illuminate\Routing\Route $route  */
		/* echo $route->uri. PHP_EOL;
      echo "<br>";*/
	}
	Page::insert($getRouteList);
});
Auth::routes();
Route::prefix('admin')->group(function () {
	Route::get('login', 'Auth\LoginController@showLoginForm');
	Route::get('sign_up', 'Auth\RegisterController@showRegistrationForm');
	Route::post('login', 'Auth\LoginController@login');
	Route::post('sign_up', 'Auth\RegisterController@register');
	Route::post('logout', 'Auth\LoginController@logout');
	Route::get('password/reset', 'Auth\ForgotPasswordController@showLinkRequestForm');
	Route::post('password/email', 'Auth\ForgotPasswordController@sendResetLinkEmail')->name('admin.password.email');
	Route::get('password/reset/{token}', 'Auth\ResetPasswordController@showResetForm')->name('admin.password.reset');
	Route::get('password/update', 'Auth\ResetPasswordController@reset')->name('admin.password.update');
});


Route::prefix('admin')->middleware(['auth','checkadmin'])->group(function () {
	Route::get('dashboard', 'Admin\DashboardController@index')->name('dashboard');
	Route::resource('news', 'Admin\NewsController');
	Route::get('news_cat', 'Admin\NewsController@news_cat_index');
	Route::get('news_cat/create', 'Admin\NewsController@news_cat_create');
	Route::post('news_cat/store', 'Admin\NewsController@news_cat_store');
	Route::get('news_cat/edit/{id}', 'Admin\NewsController@news_cat_edit');
	Route::put('news_cat/update/{id}', 'Admin\NewsController@news_cat_update');
	Route::delete('news_cat_destroy/{id}', 'Admin\NewsController@news_cat_destroy');
	Route::delete('news_cat_delete', 'Admin\NewsController@news_cat_delete');
	Route::delete('news_delete', 'Admin\NewsController@news_delete');

	Route::resource('events', 'Admin\EventController');
	Route::get('events_cat', 'Admin\EventController@events_cat_index');
	Route::get('events_cat/create', 'Admin\EventController@events_cat_create');
	Route::post('events_cat/store', 'Admin\EventController@events_cat_store');
	Route::get('events_cat/edit/{id}', 'Admin\EventController@events_cat_edit');
	Route::put('events_cat/update/{id}', 'Admin\EventController@events_cat_update');
	Route::delete('events_cat_destroy/{id}', 'Admin\EventController@events_cat_destroy');
	Route::delete('events_cat_delete', 'Admin\EventController@events_cat_delete');
	Route::delete('events_delete', 'Admin\EventController@events_delete');

	Route::resource('dedications', 'Admin\DedicationController');
	Route::delete('dedications_delete', 'Admin\DedicationController@dedication_delete');

	Route::resource('contests', 'Admin\ContestController');
	Route::get('contests_cat', 'Admin\ContestController@contests_cat_index');
	Route::get('contests_cat/create', 'Admin\ContestController@contests_cat_create');
	Route::post('contests_cat/store', 'Admin\ContestController@contests_cat_store');
	Route::get('contests_cat/edit/{id}', 'Admin\ContestController@contests_cat_edit');
	Route::put('contests_cat/update/{id}', 'Admin\ContestController@contests_cat_update');
	Route::delete('contests_cat_destroy/{id}', 'Admin\ContestController@contests_cat_destroy');
	Route::delete('contests_cat_delete', 'Admin\ContestController@contests_cat_delete');
	Route::delete('contests_delete', 'Admin\ContestController@contests_delete');

	Route::resource('sliders', 'Admin\SliderController');
	Route::delete('sliders_delete', 'Admin\SliderController@slider_delete');

	Route::resource('podcasts', 'Admin\PodcastsContorller');
	Route::get('podcasts_cat', 'Admin\PodcastsContorller@podcasts_cat_index');
	Route::get('podcasts_cat/create', 'Admin\PodcastsContorller@podcasts_cat_create');
	Route::post('podcasts_cat/store', 'Admin\PodcastsContorller@podcasts_cat_store');
	Route::get('podcasts_cat/edit/{id}', 'Admin\PodcastsContorller@podcasts_cat_edit');
	Route::put('podcasts_cat/update/{id}', 'Admin\PodcastsContorller@podcasts_cat_update');
	Route::delete('podcasts_cat_destroy/{id}', 'Admin\PodcastsContorller@podcasts_cat_destroy');
	Route::delete('podcasts_cat_delete', 'Admin\PodcastsContorller@podcasts_cat_delete');
	Route::delete('podcasts_delete', 'Admin\PodcastsContorller@podcasts_delete');

	Route::resource('playlists', 'Admin\PlaylistController');
	Route::get('playlists_cat', 'Admin\PlaylistController@playlists_cat_index');
	Route::get('playlists_cat/create', 'Admin\PlaylistController@playlists_cat_create');
	Route::post('playlists_cat/store', 'Admin\PlaylistController@playlists_cat_store');
	Route::get('playlists_cat/edit/{id}', 'Admin\PlaylistController@playlists_cat_edit');
	Route::put('playlists_cat/update/{id}', 'Admin\PlaylistController@playlists_cat_update');
	Route::delete('playlists_cat_destroy/{id}', 'Admin\PlaylistController@playlists_cat_destroy');
	Route::delete('playlists_cat_delete', 'Admin\PlaylistController@playlists_cat_delete');
	Route::delete('playlists_delete', 'Admin\PlaylistController@playlists_delete');

	Route::resource('artists', 'Admin\ArtistController');
	Route::get('artists_cat', 'Admin\ArtistController@artists_cat_index');
	Route::get('artists_cat/create', 'Admin\ArtistController@artists_cat_create');
	Route::post('artists_cat/store', 'Admin\ArtistController@artists_cat_store');
	Route::get('artists_cat/edit/{id}', 'Admin\ArtistController@artists_cat_edit');
	Route::put('artists_cat/update/{id}', 'Admin\ArtistController@artists_cat_update');
	Route::delete('artists_cat_destroy/{id}', 'Admin\ArtistController@artists_cat_destroy');
	Route::delete('artists_cat_delete', 'Admin\ArtistController@artists_cat_delete');
	Route::delete('artists_delete', 'Admin\ArtistController@artists_delete');

	Route::resource('livefeeds', 'Admin\LivefeedController');
	Route::delete('livefeeds_delete', 'Admin\LivefeedController@livefeeds_delete');


	Route::resource('pages', 'Admin\PageController');
	Route::get('pages_cat', 'Admin\PageController@pages_cat_index');
	Route::get('pages_cat/create', 'Admin\PageController@pages_cat_create');
	Route::post('pages_cat/store', 'Admin\PageController@pages_cat_store');
	Route::get('pages_cat/edit/{id}', 'Admin\PageController@pages_cat_edit');
	Route::put('pages_cat/update/{id}', 'Admin\PageController@pages_cat_update');
	Route::delete('pages_cat_destroy/{id}', 'Admin\PageController@pages_cat_destroy');
	Route::delete('pages_cat_delete', 'Admin\PageController@pages_cat_delete');
	Route::delete('pages_delete', 'Admin\PageController@pages_delete');

	Route::resource('teams', 'Admin\TeamController');
	Route::get('teams_cat', 'Admin\TeamController@teams_cat_index');
	Route::get('teams_cat/create', 'Admin\TeamController@teams_cat_create');
	Route::post('teams_cat/store', 'Admin\TeamController@teams_cat_store');
	Route::get('teams_cat/edit/{id}', 'Admin\TeamController@teams_cat_edit');
	Route::put('teams_cat/update/{id}', 'Admin\TeamController@teams_cat_update');
	Route::delete('teams_cat_destroy/{id}', 'Admin\TeamController@teams_cat_destroy');
	Route::delete('teams_cat_delete', 'Admin\TeamController@teams_cat_delete');
	Route::delete('teams_delete', 'Admin\TeamController@teams_delete');

	Route::resource('programs', 'Admin\ProgramController');
	Route::get('programs_cat', 'Admin\ProgramController@programs_cat_index');
	Route::get('programs_cat/create', 'Admin\ProgramController@programs_cat_create');
	Route::post('programs_cat/store', 'Admin\ProgramController@programs_cat_store');
	Route::get('programs_cat/edit/{id}', 'Admin\ProgramController@programs_cat_edit');
	Route::put('programs_cat/update/{id}', 'Admin\ProgramController@programs_cat_update');
	Route::delete('programs_cat_destroy/{id}', 'Admin\ProgramController@programs_cat_destroy');
	Route::delete('programs_cat_delete', 'Admin\ProgramController@programs_cat_delete');
	Route::delete('programs_delete', 'Admin\ProgramController@programs_delete');

	Route::resource('tracks', 'Admin\TrackController');
	Route::delete('tracks_delete', 'Admin\TrackController@tracks_delete');

	Route::resource('gallerys', 'Admin\GalleryController');
	Route::get('gallerys_cat', 'Admin\GalleryController@gallerys_cat_index');
	Route::get('gallerys_cat/create', 'Admin\GalleryController@gallerys_cat_create');
	Route::post('gallerys_cat/store', 'Admin\GalleryController@gallerys_cat_store');
	Route::get('gallerys_cat/edit/{id}', 'Admin\GalleryController@gallerys_cat_edit');
	Route::put('gallerys_cat/update/{id}', 'Admin\GalleryController@gallerys_cat_update');
	Route::delete('gallerys_cat_destroy/{id}', 'Admin\GalleryController@gallerys_cat_destroy');
	Route::delete('gallerys_cat_delete', 'Admin\GalleryController@gallerys_cat_delete');
	Route::delete('gallerys_delete', 'Admin\GalleryController@gallerys_delete');
	Route::get('photos', 'Admin\GalleryController@gallerys_photos');
	Route::post('gallerys/photos_store', 'Admin\GalleryController@gallerys_photos_store');
	Route::delete('photo_delete/{gallery_id}/{photo_id}', 'Admin\GalleryController@photo_delete');

	Route::resource('videos', 'Admin\VideoController');
	Route::get('videos_cat', 'Admin\VideoController@videos_cat_index');
	Route::get('videos_cat/create', 'Admin\VideoController@videos_cat_create');
	Route::post('videos_cat/store', 'Admin\VideoController@videos_cat_store');
	Route::get('videos_cat/edit/{id}', 'Admin\VideoController@videos_cat_edit');
	Route::put('videos_cat/update/{id}', 'Admin\VideoController@videos_cat_update');

app/News.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Carbon\Carbon;

class News extends Model
{
	protected $table = 'news';
	protected $fillable = ['title','image','views','publish_time','publish','end_time','description','news_cat_id'];

	public function getPublishTimeAttribute($value)
	{
		//return $value;
		$publish_time = "";
		if($value) {
			$publish_time = Carbon::parse($value)->isoFormat('D-MM-YYYY H:mm:ss');
		}        
		return $publish_time;
	}
	public function getEndTimeAttribute($value)
	{
		$end_time = "";
		if($value) {
			$end_time = Carbon::parse($value)->isoFormat('D-MM-YYYY  H:mm:ss');
		}	
		return $end_time;
	}
	public function getSlugAttribute($value) {
		return  ($this->id.'-'.str_replace(' ','-',str_replace('/','-',$this->title)));
	} 

	public function setPublishTimeAttribute($value)
	{		
		if($value) {
			$this->attributes['publish_time'] = Carbon::parse($value)->isoFormat('YYYY-MM-D H:mm:ss');
		}
		else {
			$this->attributes['publish_time'] = $value;
		}
	}
	public function setEndTimeAttribute($value)
	{		
		if($value) {
			$this->attributes['end_time'] = Carbon::parse($value)->isoFormat('YYYY-MM-D H:mm:ss');
		}
		else {
			$this->attributes['end_time'] = $value;
		}
	}


	public function cat() {
		return $this->belongsTo('App\NewsCat','news_cat_id');
	}
}

resources/views/artists.blade.php
@if(! isset($notpushstate) || ($notpushstate != '1'))
@extends('layouts.web')
@section('slider')
@endif
<div class="container m-b-15 centered">
</div>
<div class="container breadcrumb-container">
	<div class="container p-l-0 p-r-0">
		<ol class="breadcrumb ellipsis ellipsis-1l">
			<li><a href="{{url('/home')}}" class="toptip detail" title="Home"><i class="fa fa-home"></i></a></li>
			<li class="active">Artists</li>
		</ol>
	</div>
</div>
<div class="title-super-container container">
	<div class="container title-container">
		<div class="row">
			<div class="col-xs-12 layout-title p-t-20 p-b-30">
				<div>
					<h1 class="main_title">
						Artists
						<a class="rss-link" href="#" target="_blank">
							<img class="rss-logo" style="width: 13px; margin-top: 1px;" src="{{url('public/img/rss.png')}}" />
							<span class="m-l-0 m-r-0 rss-text">RSS</span>
						</a>
					</h1>
				</div>
			</div>
		</div>
	</div>
</div>
@if(! isset($notpushstate) || ($notpushstate != '1'))
@endsection
@section('content')
@endif
<div class="container body_wrap boxed">
	<div class="layout-headtitle-border"></div>
	<div class="row">
		<div class="col-xs-12  col-md-8  list_display">
			<!-- Affichage contenu -->
			<div class="m-t-30">
				<div class="centered">
					<ul class="pagination pagination-custom pagination-xs pagination-artiste">
						<li>
							<a href="{{url('artists?name=all')}}"><span class="@if(isset($pages['name']) && $pages['name'] == 'all' ) deactive @endif">All</span></a>
						</li>
						@for ($c = 65; $c <= 90; ++$c) 
						<li>
							<a href="{{url('artists?name='.chr($c))}}"><span class="@if(isset($pages['name']) && $pages['name'] == chr($c) ) deactive @endif">{{chr($c)}}</span></a>
						</li> 
						@endfor
					</ul>
				</div>
				<div class="article">
					@foreach($pages['artists'] as $artist)
					<div class="col-xs-3 col-md-3 m-b-30">
						<div class="col-xs-12 p-l-0 p-r-0">
							<a class="whole-div-link detail" href="{{url('artist_detail/'.$artist->slug)}}" class="list-action-zone">
								<div class="cover-preview list-img-zone">
									<img class="list-img-thumb  square_158"  src="{{url('public/uploads/'.$artist->image)}}">
								</div>
							</a>
						</div>
					</div>
					@endforeach
				</div>
			</div>
			<div class="pagination">
				{{$pages['artists']->links()}}
			</div>
		</div>
		<div class="hidden-xs hidden-sm col-md-4" id="sidebar">
			@foreach($sidebars as $sidebar)
			@include('aside.'.$sidebar)
			@endforeach
		</div>
	</div>
</div>
</div>
@if(! isset($notpushstate) || ($notpushstate != '1'))
@endsection
@endif

resources/views/event_detail.blade.php
@if(! isset($notpushstate) || ($notpushstate != '1'))
@extends('layouts.web')
@section('content')
@endif
<script type="text/javascript"></script>

<div class="container m-b-15 centered">
</div>

<div class="container breadcrumb-container">
	<div class="container p-l-0 p-r-0">
		<ol class="breadcrumb ellipsis ellipsis-1l">
			<li><a href="{{url('/')}}" class="toptip detail" title="Home"><i class="fa fa-home"></i></a></li>
			<li><a href="{{url('events')}}" class="detail">Events</a></li>
			<li><a href="#">{{$event->title}}</a></li>
			<li class="active">{{$event->title}}</li>
		</ol>
	</div>
</div>



<div class="title-super-container container">
	<div class="container title-container">
		<div class="row">
			<div class="col-xs-12 layout-title p-t-20 p-b-30">
				<div>
					<h1 class="main_title">
						{{$event->title}}
					</h1>
				</div>
			</div>
		</div>
	</div>
</div>

<div class="container body_wrap boxed">
	<div class="layout-headtitle-border"></div>


	<div class="row">

		<div class="col-xs-12  col-md-8  ">
			<div class="m-t-30">
				<div class="article afficher-content">
					<div class="wrap">
						<img src="{{url('public/uploads/'.$event->image)}}" style="width: 100%;" class="img-responsive m-b-5 m-t-20 rect_750_450" />
						<span class="infos-article">
							<i class="fa fa-clock"></i>{{ \Carbon\Carbon::parse($event->publish_time)->isoFormat('MMMM Do YYYY, h:mm:ss a')}}
						</span>
						<div class="m-t-15 m-b-15"></div>
						<p>{{$event->des}}</p>
					</div>
				</div>
				<div id="comments" class="row comment-row m-t-20">
					<div class="col-xs-12">
						<!-- COMMENTAIRES -->
						<div class="form-group">
							<span class="comment-img avatar-default"><i class="fa fa-user"></i></span>
							<div class="fb-comments" data-href="{{request()->fullUrl()}}" data-width="" data-numposts="5"></div>
						</div>

						<div class="form-group" style="float:right;">
							<div class="col-xs-3">
								<a href="javascript:void(0)" id="sendComment" class="btn btn-primary">Comment</a>
							</div>
						</div>
						<div class="clear"></div>
						<div id="list-comments">

						</div>

						<div class="row">
							<div class="col-xs-12">
							</div>
						</div>

						<!-- Fin commentaires -->
					</div>
				</div>
				<div id="fb-root"></div>
				<script crossorigin="anonymous" src="https://connect.facebook.net/en_GB/sdk.js#xfbml=1&version=v4.0"></script>
			</div>
		</div>
	</div>
</div>
@if(! isset($notpushstate) || ($notpushstate != '1'))
@endsection
@endif

resources/views/news.blade.php
@if(!isset($notpushstate) || ($notpushstate != 1))
@extends('layouts.web')
@section('slider')
@endif
<div class="title-super-container container">
	<div class="container title-container">
		<div class="row">
			<div class="col-xs-12 layout-title p-t-20 p-b-30">
				<div>
					<h1 class="main_title">
						News <a class="rss-link" href="#" target="_blank"><img class="rss-logo" style="width: 13px; margin-top: 1px;" src="{{url('public/img/rss.png')}}" /><span class="m-l-0 m-r-0 rss-text">RSS</span></a>
					</h1>
				</div>
			</div>
		</div>
	</div>
</div>
@if(! isset($notpushstate) || ($notpushstate != 1))
@endsection
@section('content')
@endif
<div class="container body_wrap boxed">
	<div class="layout-headtitle-border"></div>
	<div class="row">
		<div class="col-xs-12  col-md-8  list_display">
			<!-- Affichage contenu -->
			<div class="m-t-30">
				@foreach($pages['news'] as $new)
				@if($loop->index == 0)
				<div class="row first_element list_element light_shadow boxed m-l-0 m-r-0 m-b-30 ">
					<div class="col-sm-6 col-img p-l-0 p-r-0">
						<a class="whole-div-link detail" href="{{url('news_detail/'.$new->slug)}}">
							<div class="cover-preview list-img-zone">
								<img class="list-img-thumb news_sidebar_first" src="{{url('public/uploads/'.$new->image)}}">
							</div>
						</a>
					</div>
					<div class="col-sm-6 p-l-10-xs p-r-10-xs">
						<a class="whole-div-link detail" href="{{url('news_detail/'.$new->slug)}}"/>
							<h2 class="ellipsis ellipsis-3l m-t-0 m-t-10-xs m-b-10">
								{{$new->title}}
							</h2>
						</a>
						<span class="ellipsis ellipsis-4l hidden-xs list_text">
							{{$new->description}}
						</span>
						<span class="trans list_trans hidden-xs">
							{{\Carbon\Carbon::now()->diffInDays(\Carbon\Carbon::parse($new->created_at))}} Days Ago
						</span>
					</div>
				</div>
				@else
				<div class="row other_elements list_element light_shadow boxed m-l-0 m-r-0 m-b-20 ">
					<div class="col-xs-4 p-l-0 p-r-0">
						<a class="whole-div-link img-link detail" href="{{url('news_detail/'.$new->slug)}}" >
							<div class="cover-preview list-img-zone">
								<img class="list-img-thumb news_sidebar_other" src="{{url('public/uploads/'.$new->image)}}">
							</div>
						</a>
					</div>
					<div class="col-xs-8 p-r-10-xs">
						<span class="trans list_trans hidden-xxs">
							{{\Carbon\Carbon::now()->diffInDays(\Carbon\Carbon::parse($new->created_at))}} Days Ago
						</span>

						<a class="whole-div-link title-link detail" href="{{url('news_detail/'.$new->slug)}}">
							<h4 class="ellipsis ellipsis-2l m-t-10 m-b-10 m-t-5-xs m-b-0-xs">
								{{$new->title}}
							</h4>
						</a>
						<span class="ellipsis ellipsis-2l hidden-xs list_text">
							{{$new->description}}
						</span>
					</div>
				</div>
				@endif
				@endforeach
			</div>
			<div class="pagination">
				{{$pages['news']->links()}}
			</div>
		</div>

		<div class="hidden-xs hidden-sm col-md-4" id="sidebar">
			@foreach($sidebars as $sidebar)
			@include('aside.'.$sidebar)
			@endforeach
		</div>
	</div>
</div>
@if(! isset($notpushstate) || ($notpushstate != 1))
@endsection
@endif

resources/views/teams.blade.php
@if(! isset($notpushstate) || ($notpushstate != '1'))
@extends('layouts.web')
@section('slider')
@endif
<div class="container breadcrumb-container">
	<div class="container p-l-0 p-r-0">
		<ol class="breadcrumb ellipsis ellipsis-1l">
			<li><a href="{{url('/homes')}}" class="toptip detail" title="Home"><i class="fa fa-home"></i></a></li>
			<li class="active">Teams</li>
		</ol>
	</div>
</div>
<div class="title-super-container container">
	<div class="container title-container">
		<div class="row">
			<div class="col-xs-12 layout-title p-t-20 p-b-30">
				<div>
					<h1 class="main_title">
						Teams
						<a class="rss-link" href="#" target="_blank">
							<img class="rss-logo" style="width: 13px; margin-top: 1px;" src="{{url('public/img/rss.png')}}" />
							<span class="m-l-0 m-r-0 rss-text">RSS</span>
						</a>
					</h1>
				</div>
			</div>
		</div>
	</div>
</div>
@if(! isset($notpushstate) || ($notpushstate != '1'))
@endsection
@section('content')
@endif
<div class="container body_wrap boxed">
	<div class="layout-headtitle-border"></div>
	<div class="row">
		<div class="col-xs-12  col-md-8  list_display">
			<!-- Affichage contenu -->
			<div class="m-t-30">


				@foreach($pages['teams'] as $team)
				<div class="row other_elements list_element light_shadow boxed m-l-0 m-r-0 m-b-20 discounted-item lundi mardi mercredi jeudi vendredi ">
					<div class="col-xs-4 p-l-0 p-r-0">
						<a class="whole-div-link img-link detail" href="{{url('team_detail/'.$team->slug)}}" class="list-action-zone">
							<div class="cover-preview list-img-zone">
								<img class="list-img-thumb news_sidebar_other" src="{{url('public/uploads/'.$team->image)}}">
							</div>
						</a>
					</div>
					<div class="col-xs-8 p-r-10-xs">

						<a class="whole-div-link title-link detail" href="{{url('team_detail/'.$team->slug)}}" class="list-action-zone">
							<h4 class="ellipsis ellipsis-2l m-t-10 m-b-10 m-t-5-xs m-b-0-xs">
								{{$team->name}} </h4>
						</a>
						<div class="m-t-0 m-b-15 m-b-0-xs team-date">
							@if($team->publish_time)
							{{ \Carbon\Carbon::parse($team->publish_time)->isoFormat('MMMM Do YYYY, h:mm:ss a')}}
							@endif </div>
						<span class="ellipsis ellipsis-2l hidden-xs list_text">
							{{$team->description}}
						</span>
					</div>
				</div>
				@endforeach
			</div>
				<div class="pagination">
					{{$pages['teams']->links()}}
				</div>
		</div>

		<div class="hidden-xs hidden-sm col-md-4" id="sidebar">
			@foreach($sidebars as $sidebar)
			@include('aside.'.$sidebar)
			@endforeach

		</div>
	</div>
</div>
</div>
@if(! isset($notpushstate) || ($notpushstate != '1'))
@endsection
@endif

resources/views/videos.blade.php
@if(! isset($notpushstate) || ($notpushstate != '1'))
@extends('layouts.web')
@section('slider')
@endif
<div class="container m-b-15 centered">
</div>
<div class="container breadcrumb-container">
	<div class="container p-l-0 p-r-0">
		<ol class="breadcrumb ellipsis ellipsis-1l">
			<li><a href="{{url('/home')}}" class="toptip detail" title="Home"><i class="fa fa-home"></i></a></li>
			<li class="active">Video</li>
		</ol>
	</div>
</div>
<div class="title-super-container container">
	<div class="container title-container">
		<div class="row">
			<div class="col-xs-12 layout-title p-t-20 p-b-30">
				<div>
					<h1 class="main_title">
						Video
						<a class="rss-link" href="#" target="_blank">
							<img class="rss-logo" style="width: 13px; margin-top: 1px;" src="{{url('public/img/rss.png')}}" />
							<span class="m-l-0 m-r-0 rss-text">RSS</span>
						</a>
					</h1>
				</div>
			</div>
		</div>
	</div>
</div>
@if(! isset($notpushstate) || ($notpushstate != '1'))
@endsection
@section('content')
@endif
<div class="container body_wrap boxed">
	<div class="layout-headtitle-border"></div>
	<div class="row">
		<div class="col-xs-12  col-md-8  list_display">
			<!-- Affichage contenu -->
			<div class="m-t-30">
				@foreach($pages['videos'] as $video)
				<div class="row other_elements list_element light_shadow boxed m-l-0 m-r-0 m-b-20 discounted-item lundi mardi mercredi jeudi vendredi ">
					<div class="col-xs-4 p-l-0 p-r-0">
						<a class="whole-div-link img-link detail" href="{{url('video_detail/'.$video->slug)}}" class="list-action-zone">
							<div class="cover-preview list-img-zone">
								<img class="list-img-thumb news_sidebar_other" src="{{url('public/uploads/'.$video->image)}}">
							</div>
						</a>
					</div>
					<div class="col-xs-8 p-r-10-xs">

						<a class="whole-div-link title-link detail" href="{{url('video_detail/'.$video->slug)}}" class="list-action-zone">
							<h4 class="ellipsis ellipsis-2l m-t-10 m-b-10 m-t-5-xs m-b-0-xs">
								{{$video->title}} </h4>
						</a>
						<div class="m-t-0 m-b-15 m-b-0-xs video-date">
							@if($video->publish_time)
							{{ \Carbon\Carbon::parse($video->publish_time)->isoFormat('MMMM Do YYYY, h:mm:ss a')}}
							@endif </div>
						<span class="ellipsis ellipsis-2l hidden-xs list_text">
							{{$video->description}}
						</span>
					</div>
				</div>
				@endforeach
			</div>
				<div class="pagination">
					{{$pages['videos']->links()}}
				</div>
		</div>

		<div class="hidden-xs hidden-sm col-md-4" id="sidebar">
		@foreach($sidebars as $sidebar)
		@include('aside.'.$sidebar)
		@endforeach
		</div>
	</div>
</div>
</div>
@if(! isset($notpushstate) || ($notpushstate != '1'))
@endsection
@endif